fluxnova:
  user:
    id: ${TEST_USER_ID}
    firstName: "DefaultUser"
    lastName: "Example"
    email: "default@example.com"
    password: ${TEST_USER_PASSWORD}
  groups:
    - id: "fluxnovabpmusers"
      name: "Fluxnoav BPM Users"
      type: "SYSTEM"
  authorization:
    - type: 1
      resourceId: "*"

